<h1>
    Tasks
</h1>

<ul>
    <?php
    /** @var \App\Model\TaskModel $task */
    foreach ($this->tasks as $task) {
        ?>
        <li>
            <div>User: <?=htmlspecialchars($task->getUsername(), ENT_QUOTES, 'UTF-8');?></div>
            <div>Email: <?=htmlspecialchars($task->getEmail(), ENT_QUOTES, 'UTF-8');?></div>
            <div>Content: <?=htmlspecialchars($task->getContent(), ENT_QUOTES, 'UTF-8');?></div>
            <div>State: <?=$task->getState() === 0 ? 'Active' : 'Done'?></div>
        </li>
        <?php
    }
    ?>

    <div>
        <?php
            $pages = $this->paginator->getPages();
            foreach ($pages as $page) {
                ?>
                <span style="width:50px; height: 50px; color: black; background-color: lightblue"
                      class="<?=$page['isActive'] ? 'active' : ''?>">
                    <a href="/?page=<?=$page['page']?>"><?=$page['page']?></a>
                </span>
        <?php
            }
        ?>
    </div>
</ul>