<h2>
    Create Task
</h2>

<form action="/?action=createtask" method="post">
    <div>
        <label for="username">Username</label>
        <input type="text" id="username" name="username">
    </div>
    <div>
        <label for="email">E-mail</label>
        <input type="text" id="email" name="email">
    </div>
    <div>
        <label for="content">Content</label>
        <textarea id="content" name="content"></textarea>
    </div>
    <div>
        <button type="submit">Create Task</button>
    </div>
</form>

<h2>
    Tasks
</h2>

<ul>
    <?php
    /** @var \App\Model\TaskModel $task */
    foreach ($this->tasks as $task) {
        ?>
        <li>
            <div>User: <?=htmlspecialchars($task->getUsername(), ENT_QUOTES, 'UTF-8');?></div>
            <div>Email: <?=htmlspecialchars($task->getEmail(), ENT_QUOTES, 'UTF-8');?></div>
            <div>Content: <?=htmlspecialchars($task->getContent(), ENT_QUOTES, 'UTF-8');?></div>
            <div>State: <?=$task->getState() === 0 ? 'Active' : 'Done'?></div>
        </li>
        <?php
    }
    ?>

    <div>
        <?php
            $pages = $this->paginator->getPages();
            foreach ($pages as $page) {
                ?>
                <span style="width:50px; height: 50px; color: black; background-color: lightblue"
                      class="<?=$page['isActive'] ? 'active' : ''?>">
                    <a href="/?page=<?=$page['page']?>"><?=$page['page']?></a>
                </span>
        <?php
            }
        ?>
    </div>
</ul>